In [1]:
import pandas as pd

## Data

In [91]:
df = pd.read_csv("../news_stock_price.csv")

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145689 entries, 0 to 145688
Data columns (total 26 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   title                    145689 non-null  object 
 1   url                      145689 non-null  object 
 2   time_published           145689 non-null  object 
 3   authors                  145689 non-null  object 
 4   summary                  145677 non-null  object 
 5   banner_image             141418 non-null  object 
 6   source                   145689 non-null  object 
 7   category_within_source   46206 non-null   object 
 8   source_domain            145689 non-null  object 
 9   topics                   145689 non-null  object 
 10  overall_sentiment_score  145689 non-null  float64
 11  overall_sentiment_label  145689 non-null  object 
 12  ticker_sentiment         145689 non-null  object 
 13  company                  145689 non-null  object 
 14  symb

In [93]:
df

title  \
0       Schwab  ( SCHW )  February Client Assets Fall ...   
1       Should Schwab Fundamental U.S. Small Company I...   
2       Schwab  ( SCHW )  Expands Crypto Exposure, Fil...   
3       Women deserve respect around money and investi...   
4                  Is Charles Schwab Stock Fairly Priced?   
...                                                   ...   
145684  Ericsson  ( ERIC )  Sets Up Quantum Research H...   
145685  Here's Why Juniper  ( JNPR )  is a Healthy Inv...   
145686  Arista  ( ANET )  Offers Improved, Modernized ...   
145687  5G IoT Market worth $59.7 billion by 2028 - Ex...   
145688  Buy These 4 Mutual Funds to Protect Against Ma...   

                                                      url  \
0       https://www.zacks.com/stock/news/1882042/schwa...   
1       https://www.zacks.com/stock/news/1879406/shoul...   
2       https://www.zacks.com/stock/news/1877593/schwa...   
3       https://www.marketwatch.com/story/women-deserv...   
4       https://www.forbes.com/sites/greatspeculations...   
...                                                   ...   
145684  https://www.zacks.com/stock/news/2068552/erics...   
145685  https://www.zacks.com/stock/news/2069118/heres...   
145686  https://www.zacks.com/stock/news/2069120/arist...   
145687  https://www.prnewswire.com/news-releases/5g-io...   
145688  https://www.zacks.com/stock/news/2066579/buy-t...   

             time_published                        authors  \
0       2022-03-15 12:22:00  ['Zacks Investment Research']   
1       2022-03-09 11:20:06  ['Zacks Investment Research']   
2       2022-03-04 15:24:00  ['Zacks Investment Research']   
3       2022-03-09 12:10:00    ['Carrie Schwab-Pomerantz']   
4       2022-03-25 10:30:34                ['Trefis Team']   
...                     ...                            ...   
145684  2023-03-21 13:08:00  ['Zacks Investment Research']   
145685  2023-03-22 14:09:00  ['Zacks Investment Research']   
145686  2023-03-22 14:11:00  ['Zacks Investment Research']   
145687  2023-03-24 14:30:00          ['MarketsandMarkets']   
145688  2023-03-16 11:10:00  ['Zacks Investment Research']   

                                                  summary  \
0       Unfavorable markets hurt Schwab's (SCHW) total...   
1                           Style Box ETF report for FNDA   
2       Schwab (SCHW) files for a crypto economy ETF w...   
3       Sexism and stereotypes deter women from buildi...   
4       Charles Schwab's stock has gained roughly 7% Y...   
...                                                   ...   
145684  Ericsson's (ERIC) quantum research hub is like...   
145685  Juniper (JNPR) is set to capitalize on the gro...   
145686  The Arista (ANET) solution will enable custome...   
145687  5G IoT Market worth $59.7 billion by 2028 - Ex...   
145688  Invest in mutual funds like FSUTX, PRUZX, FRUA...   

                                             banner_image            source  \
0       https://staticx-tuner.zacks.com/images/article...  Zacks Commentary   
1       https://staticx-tuner.zacks.com/images/default...  Zacks Commentary   
2       https://staticx-tuner.zacks.com/images/article...  Zacks Commentary   
3                https://images.mktw.net/im-496327/social       MarketWatch   
4       https://imageio.forbes.com/specials-images/ima...            Forbes   
...                                                   ...               ...   
145684  https://staticx-tuner.zacks.com/images/article...  Zacks Commentary   
145685  https://staticx-tuner.zacks.com/images/article...  Zacks Commentary   
145686  https://staticx-tuner.zacks.com/images/article...  Zacks Commentary   
145687  https://mma.prnewswire.com/media/660509/Market...       PR Newswire   
145688  https://staticx-tuner.zacks.com/images/article...  Zacks Commentary   

       category_within_source        source_domain  \
0                         NaN        www.zacks.com   
1                         NaN        www.zacks.com 

## Finbert (Prosus AI)

https://huggingface.co/ProsusAI/finbert

In [16]:
import torch

In [67]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")

model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")

softmax = torch.nn.Softmax(dim=-1)

## Single sentence

#LABEL_0: positive; LABEL_1: negative; LABEL_2: neutral

In [78]:
def process_single_sentence(tokenizer, model, softmax, sentence, verbose=True):
    inputs = tokenizer(sentence, return_tensors="pt")
    if verbose:
        print(f"Tokens: {inputs}\n")
    outputs = model(**inputs)
    if verbose:
        print(f"Logits: {outputs.logits}")
    prob = softmax(outputs.logits)
    return prob

In [83]:
sentences = ["Stocks rallied and the British pound gained.", "profits are flat"]

for sent in sentences:
    print(sent)
    prob = process_single_sentence(tokenizer, model, softmax, sent, verbose=False)
    print(prob)
    print("\n")

Stocks rallied and the British pound gained.
tensor([[0.8984, 0.0345, 0.0672]], grad_fn=<SoftmaxBackward0>)


profits are flat
tensor([[0.2225, 0.0589, 0.7186]], grad_fn=<SoftmaxBackward0>)




## Multiple sentences

In [84]:
def process_multiple_sentence(tokenizer, model, softmax, sentences, verbose=True):
    inputs = tokenizer(sentences, return_tensors="pt", padding=True)
    if verbose:
        print(f"Tokens: {inputs}\n")
    outputs = model(**inputs)
    if verbose:
        print(f"Logits: {outputs.logits}")
    prob = softmax(outputs.logits)
    return prob

In [85]:
sentences = ["Stocks rallied and the British pound gained.", "profits are flat"]
process_multiple_sentence(tokenizer, model, softmax, sentences, verbose=False)

tensor([[0.8984, 0.0345, 0.0672],
        [0.2225, 0.0589, 0.7186]], grad_fn=<SoftmaxBackward0>)

## Finbert (yiyanghkust)

https://huggingface.co/yiyanghkust/finbert-tone

#LABEL_0: neutral; LABEL_1: positive; LABEL_2: negative

In [88]:
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import pipeline

tokenizer = BertTokenizer.from_pretrained('yiyanghkust/finbert-tone')

model = BertForSequenceClassification.from_pretrained('yiyanghkust/finbert-tone',num_labels=3)

softmax = torch.nn.Softmax(dim=-1)
# nlp = pipeline("sentiment-analysis", model=finbert, tokenizer=tokenizer)

## Single sentence

In [89]:
sentences = ["there is a shortage of capital, and we need extra financing",  
             "growth is strong and we have plenty of liquidity", 
             "there are doubts about our finances", 
             "profits are flat"]

for sent in sentences:
    print(sent)
    prob = process_single_sentence(tokenizer, model, softmax, sent, verbose=False)
    print(prob)
    print("\n")

there is a shortage of capital, and we need extra financing
tensor([[3.3754e-03, 7.2024e-06, 9.9662e-01]], grad_fn=<SoftmaxBackward0>)


growth is strong and we have plenty of liquidity
tensor([[2.6476e-08, 1.0000e+00, 2.1309e-08]], grad_fn=<SoftmaxBackward0>)


there are doubts about our finances
tensor([[2.6841e-05, 2.1086e-06, 9.9997e-01]], grad_fn=<SoftmaxBackward0>)


profits are flat
tensor([[0.9889, 0.0018, 0.0092]], grad_fn=<SoftmaxBackward0>)




## Multiple sentences

In [90]:
sentences = ["there is a shortage of capital, and we need extra financing",  
             "growth is strong and we have plenty of liquidity", 
             "there are doubts about our finances", 
             "profits are flat"]

process_multiple_sentence(tokenizer, model, softmax, sentences, verbose=False)

tensor([[3.3754e-03, 7.2024e-06, 9.9662e-01],
        [2.6475e-08, 1.0000e+00, 2.1309e-08],
        [2.6841e-05, 2.1086e-06, 9.9997e-01],
        [9.8894e-01, 1.8429e-03, 9.2129e-03]], grad_fn=<SoftmaxBackward0>)